version: '2'

services:
    web:
        ports:
            - '3000:3000'
            - '3001:3001'
            - '80:8080'
        command: 'npm run watch'
        volumes:
            - "./app:/app/app"
            - "./dist:/app/dist"
            - "./config:/app/config"
            - "./package.json:/app/package.json"
            - "./yarn.lock:/app/yarn.lock"
            - "./.editorconfig:/app/.editorconfig"
            - "./.flowconfig:/app/.flowconfig"
        build:
            context: .
